# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Kahro
tagline:             ''
description:         ''
url:                 http://kahrodiamonds.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Isaac Mostovicz
  url:               https://kahro.com
  email:             isaac@janusthinking.com

# Custom vars
version:             1.0.0
